import { jsonToGraphQLQuery } from 'json-to-graphql-query';

export default function getWorkRequestListByGroupStatus(obj) {
  const {
    Actionflag = '',
    HiddenControl1 = '',
    HiddenControl2 = '',
    Category = '',
    LocDesc = '',
    PlangroupCode = '',
    PlangroupDesc = '',
    Priority = '',
    status = '',
    ReportedTimeCode = '',
    Type = '',
    WorkorderNo = '',
    skip = 0,
    workrequestNo='',
    eqpDesc = '',
    fromDate = '',
    locationCode = '',
    reportedBy = '',
    srchby = '',
    srchbyinpval = '',
    toDate = '',
    workGroup = '',
    workgroupDesc = '',
    workrequestOn = '',
    equipmentCode = '',
  } = obj
  const query = {
    '': {
      workRequest_getWrkReqsBySts: {
        getthelistofWorkRequests: {
          __args: {
            HiddenControl1: HiddenControl1,
            HiddenControl2: HiddenControl2,
            Actionflag: Actionflag,
            // Actionflag: Actionflag,
            Category: Category,
            LocDesc: LocDesc,
            Priority: Priority,
            Type: Type,
            PlangroupCode: PlangroupCode,
            PlangroupDesc: PlangroupDesc,
            ReportedTimeCode: ReportedTimeCode,
            WorkorderNo: WorkorderNo,
            eqpDesc: eqpDesc,
            equipmentCode: equipmentCode,
            fromDate: fromDate,
            locationCode: locationCode,
            reportedBy: reportedBy,
            srchby: srchby,
            srchbyinpval: srchbyinpval,
            status: status,
            toDate: toDate,
            workGroup: workGroup,
            workgroupDesc: workgroupDesc,
            workrequestNo: workrequestNo,
            workrequestOn: workrequestOn,
            skip: skip,
            take: 15,
          },
          data: {
            GetWorkReqInfo: {
              autoclose: true,
              date: true,
              Guid: true,
              GetfileListinfo: {
                filesMainRef: true,
                filesIndividualRef: true,
                relativePath: true,
              },
              reportedByCodeout: true,
              reportedByNameout: true,
              equipmentCodeout: true,
              equipmentdescout: true,
              equipmentCondition: true,
              equipmentConditiondesc: true,
              Locationdesc: true,
              locationCodeout: true,
              observationDate: true,
              observationTime: true,
              observationDetails: true,
              statusout: true,
              Statusdesc: true,
              time: true,
              Typeout: true,
              Typedesc: true,
              timestamp: true,
              targetDate: true,
              workPhone: true,
              Categoryout: true,
              Categorydesc: true,
              Priorityout: true,
              problemCode: true,
              problemDesc: true,
              Prioritydesc: true,
              wrDesc: true,
              WorkOrderNo: true,
              workGroupout: true,
              Workgroupdesc: true,
              workrequestNoout: true,
              workrequestOnout: true,
              workrequestOndesc: true,
              SuggestedOrAssignedWOFlag: true,
            }
          }
        }
      }
    }
  }
  return jsonToGraphQLQuery(query, { pretty: true });
}
